name: Test Products App

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  unit-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn run test
